### PR TITLE
Update Stockfish to current development version.

### PR DESCRIPTION
**Pull request by gcp**
There are still issues with the variation display in the lichess app. Not sure if that's on Stockfish' side or an issue in the app. Hopefully this can help debug it: initialization no longer crashes.

See https://github.com/veloce/lichobile/issues/691

### CODE REVIEW

**Comment by veloce** [comment]
Great! I'll test that and hopefully be able to debug variation display (not sure what bug is that?).

I'm curious, since I've made the same changes on my side (not pushed yet) in stockfishjni.cpp and uci.cpp, so what it is that was causing the initialization crash?

**Comment by gcp** [comment]
Those changes are the only relevant ones - I assumed that because they're the ones that needed changing due to the SF update, they're the place a small bug might have crept in. If it's really **exactly** the same as yours, then this should crash for you in the same manner.

Edit: Maybe I misunderstood your question. Indeed, I think it's likely that some changes in the initialization code were missing and were causing the crash.

**Comment by gcp** [comment]
The issue with the display is almost certainly an issue with the app. Or perhaps Stockfish is displaying things different than it expects, but the SF output is right as per UCI.

This shows the bug:
https://photos.app.goo.gl/kGraXCiheK6P8Y6a7

This was the Stockfish output in logcat:
```
V/lichess (10380): out=info depth 14 seldepth 19 multipv 1 score cp 54 nodes 814426 nps 167992 hashfull 352 tbhits 0 time 4848 pv e2e4 e7e5 g1f3 g8f6 d2d4 f6e4 d4e5 d7d5 f1d3 b8c6 e1g1 f8e7 c1e3 e8g8 b1d2 e4c5 d3b5
```

**Comment by gcp** [comment]
Note that this is likely missing this patch: https://github.com/veloce/cordova-plugin-stockfish/commit/5e6454e3b32c9a6dc4a957605d748727157507bc#diff-79d9b1b1d55ae5bf86806c9b2dbee311

If it's still needed it will need to be applied on top of this pull.

**Comment by gcp** [comment]
Oh there's a bug that's resetting the FEN once too much, that's why this going wrong:

```
V/lichess (22345): cmd=position fen rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1 moves h2h3 g7g5 e2e3 h7h5
V/lichess (22345): cmd=go depth 99
V/lichess (22345): out=info depth 1 seldepth 1 multipv 1 score cp 47 nodes 495 nps 45000 tbhits 0 time 11 pv e2e4 d7d6
```

**Comment by gcp** [comment]
Ok, I believe that is working now.

I still see issues for example when switching to playing the local engine after analyzing, which seem thread related.

**Comment by gcp** [comment]
The problematic scenario right now is this: you play some games locally vs the engine, then you launch the analysis board.

Internally, this causes the plugin to exit, and I presume, attempt to be reinitialized. But this hangs.

My best guess is that not all of Stockfish's threads are being shut down properly, particularly now that uiThread exists as a static shared_ptr (which would eternally hold that thread alive). But fixing that didn't seem to make the problem go away.

Java_org_lichess_stockfish_CordovaPluginStockfish_jniExit reaches the end of that function.

The tombstone suggest it's actually the 2nd init that hangs:

```
 native: #00 pc 0003d440  /data/app/org.lichess.mobileapp-2/lib/arm/libstockfishjni.so (Position::init()+639)
  native: #01 pc 0001c66b  /data/app/org.lichess.mobileapp-2/lib/arm/libstockfishjni.so (Java_org_lichess_stockfish_CordovaPluginStockfish_jniInit+222)
  native: #02 pc 0027cfef  /data/dalvik-cache/arm/data@app@org.lichess.mobileapp-2@base.apk@classes.dex (Java_org_lichess_stockfish_CordovaPluginStockfish_jniInit__+82)
  at org.lichess.stockfish.CordovaPluginStockfish.jniInit(Native method)
  at org.lichess.stockfish.CordovaPluginStockfish.init(CordovaPluginStockfish.java:79)
  at org.lichess.stockfish.CordovaPluginStockfish.execute(CordovaPluginStockfish.java:64)
```

**Comment by gcp** [comment]
I think the cukoo tables are the cause: they're not 0-initialized at the start of Position::init(), so repeated calls of Position::init() are problematic. I'm not sure this should be considered a bug in Stockfish, because commits like a66c73deef420104e74b6645ee60e20b37fd8549 hint that that should actually work.

**Comment by gcp** [comment]
@veloce I think this is all working correctly now. Please test :-)

**Comment by veloce** [comment]
@gcp it works now! Thanks. I don't see the variation bug in the application.
Also I think we still need the aforementioned patch, it solved crashes occurring on iOS only after a longer search.

**Comment by gcp** [comment]
>I don't see the variation bug in the application.

It was fixed in one of the follow-up commits.

>Also I think we still need the aforementioned patch, it solved crashes occurring on iOS only after a longer search.

The relevant code appears to already have been included in the stockfish-variant tree, e.g.: https://github.com/veloce/cordova-plugin-stockfish/pull/9/files#diff-b074e04ad7e10a48b5d4b715ec9633b4L58 so I think we're good.

**Pull request merged**
